apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketplace-ingress
spec:
  tls:
    - hosts:
        - ec2-18-188-75-153.us-east-2.compute.amazonaws.com
      secretName: tls
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-mfe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - ec2-18-188-75-153.us-east-2.compute.amazonaws.com
      secretName: tls
  rules:
    - http:
        paths:
          - path: /angular(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: angular-sspa
                port:
                  number: 4201
          - path: /react(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mfe-react-users
                port:
                  number: 4202

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-root-ingress
spec:
  tls:
    - hosts:
        - ec2-18-188-75-153.us-east-2.compute.amazonaws.com
      secretName: tls
  defaultBackend:
    service:
      name: root-config
      port:
        number: 9000