server:
  port: 8081

spring:
  application:
    name: card-service
  datasource:
    # Connects to the docker instance on localhost port 5432
    url: jdbc:postgresql://localhost:5432/card_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: market_pass
  jpa:
    # Updated for Postgres
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.marketplace.card: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"